services:
  redis:
    image: redis:latest
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    env_file: .env.dev
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - file-storage-network

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "5540:5540"
    restart: always
    volumes:
      - redis_insight:/data
    networks:
      - file-storage-network

  minio:
    image: minio/minio
    env_file: .env.dev
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - file-storage-network

  frontend:
    build:
      context: ./frontend/cloud-storage-frontend-master/
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    networks:
      - file-storage-network

volumes:
  minio-data:
  redis-data:
  redis_insight:
  postgres-data:

networks:
  file-storage-network:
    driver: bridge